version: '3.1'

services:
  nodejs:
    depends_on:
      - postgresql
    container_name: nodejs
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3333:3333"
    volumes:
      - .:/app
      - /Back/node_modules
    environment:
      - CONNECTION_STRING='postgresql://mbert30:password@postgresql:5432/PingPongProject'
      - PORT=3333
      - USER='mbert30'
      - PASSWORD='password'
      - DATABASE='PingPongProject'
      - HOST='postgresql'
      - PORTDB=5432
    command: npm run dev
    networks:
      - app-network

  postgresql:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: PingPongProject
      POSTGRES_USER: mbert30
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge